name: First Workflow

on: push

jobs: 
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello, world!"


  say-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: say goodbye
        run: echo "Goodbye, world!"